def build_featherless_review_payload(decision_support: dict) -> dict:
    credit = decision_support["credit_readiness"]

    return {
        "farmer": decision_support["farmer"],
        "credit_readiness": {
            "provider": credit.get("provider"),
            "model_type": credit.get("model_type"),
            "model_version": credit.get("model_version"),
            "score": credit.get("score"),
            "repayment_readiness_probability": credit.get("repayment_readiness_probability"),
            "tier": credit.get("tier"),
            "recommended_loan_range": credit.get("recommended_loan_range"),
            "confidence": credit.get("confidence"),
            "loan_officer_final_decision_required": credit.get("loan_officer_final_decision_required"),
            "manual_attention_required": credit.get("manual_attention_required"),
            "positive_signals": credit.get("positive_signals", []),
            "risk_signals": credit.get("risk_signals", []),
            "technical_risk_signals": credit.get("technical_risk_signals", []),
            "missing_data": credit.get("missing_data", []),
            "alternative_data_used": credit.get("alternative_data_used", []),
            "model_reason_codes": credit.get("model_reason_codes", {}),
            "final_decision_note": credit.get("final_decision_note"),
        },
        "graph_intelligence": decision_support.get("graph_intelligence", {}),
        "decision_recommendation": decision_support["decision_recommendation"],
        "alternative_risk_intelligence": decision_support["alternative_risk_intelligence"],
        "risk_context": decision_support["risk_context"],
        "inclusion_context": decision_support["inclusion_context"],
        "fairness": decision_support["fairness"],
        "existing_farmer_message": decision_support["farmer_message"],
        "existing_officer_memo": decision_support["officer_memo"],
        "required_business_outputs": [
            "officer_decision_memo",
            "credit_committee_brief",
            "branch_action_plan",
            "farmer_sms",
            "farmer_ussd_summary",
            "data_collection_checklist",
            "risk_mitigation_notes",
            "inclusion_accessibility_note",
            "audit_explanation",
            "model_limitations",
        ],
    }